# Change these first
owner: picoscratch # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: PicoScratch Homepage
    url: https://www.picoscratch.de
  - name: PicoScratch MINT Manager
    url: https://mint.picoscratch.de
  - name: PicoScratch MINT Server
    url: https://mintsrv.picoscratch.de
    expectedStatusCodes:
      - 500
  - name: PicoScratch Learn Manager
    url: https://manager.picoscratch.de
  - name: PicoScratch Learn Server
    url: https://server.picoscratch.de

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.picoscratch.de
  # baseUrl: /your-repo-name
  logoUrl: https://avatars.githubusercontent.com/u/117832495?s=400&u=637662c98a68aa05d4f21b9edd33c2c5290b202a&v=4
  favicon: https://avatars.githubusercontent.com/u/117832495?s=400&u=637662c98a68aa05d4f21b9edd33c2c5290b202a&v=4
  name: PicoScratch
  introTitle: "**PicoScratch** status"
  introMessage: This is a status page which uses **real-time** data from our [GitHub repository](https://github.com/picoscratch/upptime).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
